trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Solution

variables:
  - group: GCP Release variable group
  - name: tag
    value: '$(Build.BuildId)'
  - template: variables.yml
        
name: ${{variables.versionBuild}}

stages:
  - template: template-build-stage.yml
    parameters:
      stageName: ${{variables.buildStage}}
      vmImage: '${{variables.vmImage}}'
      containerRegistry: ${{variables.containerRegistry}}
      repository: ${{variables.repository}}
      dockerfile: ${{variables.dockerfile}}
      condition: ne(variables['Build.Reason'], 'PullRequest')
